services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - 'com.github.nginx-proxy.nginx'
    networks: 
      - my-network

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: "mail@luca-home.de"
    networks: 
      - my-network

  frontend:
    container_name: svelte-frontend
    image: svelte-frontend
    depends_on:
      nginx-proxy:
        condition: service_started
      nginx-proxy-acme:
        condition: service_started
          # build: ./svelte-frontend
    environment:
      VIRTUAL_HOST: "luca-home.de"
      VIRTUAL_PORT: "3000"
      LETSENCRYPT_HOST: "luca-home.de"
      LETSENCRYPT_EMAIL: "mail@luca-home.de"
    networks:
      - my-network

volumes:
  certs:
  html:
  acme:
  vhost:

networks:
  my-network:
    name: my-network
    external: true
