import type { Metadata } from 'next'
import './globals.css'
import React from "react";
import NavbarMenu from "@/components/NavbarMenu/NavbarMenu";

export const metadata: Metadata = {
  title: 'Luca Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="dark">
      <body>
      <NavbarMenu/>
      {children}
      </body>
    </html>
  )
}
